#
# Save and restore all video memory allocations.
#options nvidia NVreg_PreserveVideoMemoryAllocations=1
#
# The destination should not be using tmpfs, so we prefer
# /var/tmp instead of /tmp
#options nvidia NVreg_TemporaryFilePath=/var/tmp
#
# Enable kernel suspend notifiers for open modules,
# the kernel handles video memory preservation directly
#options nvidia NVreg_UseKernelSuspendNotifiers=1
